import React from 'react';

function InfoSection() {
  return (
    <section style={{backgroundColor:'black'}} className="py-16 bg-gray-100">
      {/* Container */}
      <div className="container mx-auto px-6 md:px-12 text-center">
        {/* Heading */}
        <h1 className="text-4xl font-bold mb-4 text-white">Brands Make More Money on Postscript</h1>

        {/* Paragraph */}
        <p className="text-lg text-white mb-12">
        Our entire focus is on SMS, which is why Shopify stores have more success here than anywhere else.
        </p>

        {/* Flex container for cards */}
        <div className="flex flex-wrap justify-center gap-12">
          {/* Card 1 */}
          <div 
            style={{backgroundColor:'#17161a' , width:'250px'}} 
            className="flex flex-col items-center p-6 bg-white shadow-lg rounded-lg w-full sm:w-1/2 md:w-1/3 lg:w-1/4"
          >
            <h3 style={{color:'white'}} className="text-7xl font-extrabold">+$5B</h3>
            <p style={{color:'white'}} className="mt-4 w-60 text-gray-700 text-center">
              In revenue generated by Postscript
            </p>
          </div>

          {/* Card 2 */}
          <div 
            style={{backgroundColor:'#17161a', width:'250px'}} 
            className="flex flex-col items-center p-6 bg-white shadow-lg rounded-lg w-full sm:w-1/2 md:w-1/3 lg:w-1/4"
          >
            <h3 style={{color:'white'}} className="text-7xl font-extrabold">+22%</h3>
            <p style={{color:'white'}} className="mt-4 w-60 text-gray-700 text-center">
              Online revenue attributed to Postscript SMS
            </p>
          </div>

          {/* Card 3 */}
          <div 
            style={{backgroundColor:'#17161a' , width:'250px'}} 
            className="flex flex-col items-center p-6 bg-white shadow-lg rounded-lg w-full sm:w-1/2 md:w-1/3 lg:w-1/4"
          >
            <h3 style={{color:'white'}} className="text-7xl font-extrabold">6x</h3>
            <p style={{color:'white'}} className="mt-4 w-60 text-gray-700 text-center">
              YoY list growth rate since introducing Onsite Opt-in
            </p>
          </div>

          {/* Card 4 */}
          <div 
            style={{backgroundColor:'#17161a' , width:'250px'}} 
            className="flex flex-col items-center p-6 bg-white shadow-lg rounded-lg w-full sm:w-1/2 md:w-1/3 lg:w-1/4"
          >
            <h3 style={{color:'white'}} className="text-7xl font-extrabold">+20%</h3>
            <p style={{color:'white'}} className="mt-4 w-60 text-gray-700 text-center">
              Average revenue lift on AI beta features
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}

export default InfoSection;
